# Generated by Django 4.2.7 on 2023-11-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(choices=[('Administrador', 'Administrador'), ('Coordinador', 'Coordinador'), ('Estudiante', 'Estudiante'), ('Docente', 'Docente')], max_length=100)),
            ],
        ),
    ]
