# Generated by Django 4.2.7 on 2023-11-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='cellphone',
            field=models.CharField(max_length=10),
        ),
    ]
