# Generated by Django 4.2.7 on 2023-11-16 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_client', '0001_initial'),
        ('users_generics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_client_id_rol', to='users_generics.rol'),
        ),
    ]
