# Generated by Django 4.2.7 on 2023-11-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_client', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclient',
            name='id_rol',
        ),
    ]
